# Generated by Django 4.2.6 on 2023-10-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_alter_groupmodel_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroupModel',
            fields=[
                ('sub_group_id', models.UUIDField(primary_key=True, serialize=False)),
                ('sub_group_code', models.CharField(max_length=20)),
                ('sub_group_name', models.CharField(max_length=50)),
                ('group_code', models.CharField(max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupmodel')),
            ],
        ),
    ]
