# Generated by Django 4.2.6 on 2023-10-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subgroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroupmodel',
            name='group_code',
        ),
    ]
