# Generated by Django 4.2.6 on 2023-11-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subgroups', '0002_remove_subgroupmodel_group_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlMasterModel',
            fields=[
                ('_id', models.UUIDField(primary_key=True, serialize=False)),
                ('gl_code', models.CharField()),
                ('gl_name', models.CharField()),
                ('gl_type', models.CharField()),
                ('gl_balance', models.BigIntegerField()),
                ('gl_balance_type', models.CharField()),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subgroups.subgroupmodel')),
            ],
        ),
    ]
