# Generated by Django 4.2.6 on 2023-10-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('group_id', models.UUIDField(primary_key=True, serialize=False)),
                ('group_code', models.CharField()),
                ('group_name', models.CharField()),
                ('group_balance', models.CharField()),
                ('group_type', models.CharField()),
            ],
        ),
    ]
