# Generated by Django 4.2.6 on 2023-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='group_balance',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='group_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='group_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='group_type',
            field=models.CharField(max_length=20),
        ),
    ]
