# Generated by Django 4.2.6 on 2023-10-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groupmodel_group_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
